### ISSUE TITLE
Ankihub changes note type name, anki note type not recognized by the app

### ISSUE THREAD

**Issue by cstandi** [AnKingMed/AnKing-Note-Types#80]
#### Which Note Type (and version) is this about?
Anking overhaul from up to date as of 7/29/2022
#### Problem description
When ankihub modifies note type the anking not type app no longer recognizes the note and you lose your ability t modify it
*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
windows
*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Is your note type addon up to date?

@RisingOrange I thought we had planned for this?

**Comment by RisingOrange** [comment]
What is the name of the note type @cstandi ? The add-on should work with note type versions from AnkiHub, I just tested it again.

One thing doesn't work for them though. When you open the template editor for a note type from AnkiHub and edit it you won't see the changes reflected in the preview. However when you save the changes they will be applied to all note types versions. For example if you edit "AnKingOverhaul (deck / user)" the changes will also get applied to "AnKingOverhaul". The same also works in reverse. So it's best to edit "AnKingOverhaul" because there you can preview the changes immediately.

**Comment by RisingOrange** [comment]
Should I fix the missing preview for AnkiHub versions of note types, @AnKingMed ? Or is that acceptable?

**Comment by AnKingMed** [comment]
If it's not too difficult it'd be nice. If it's complicated then don't worry about it

**Comment by RisingOrange** [comment]
@AnKingMed 
It's unfortunately not that easy... But I could quickly add a message telling the user about this when they try to edit an AnkiHub version of a notetype.

**Comment by AnKingMed** [comment]
That's a good idea!

**Comment by RisingOrange** [comment]
Ok, I'll do this tomorrow!
