### ISSUE TITLE
Cannot change the color of "Back" in the Basic-type notes

### ISSUE THREAD

**Issue by Farinata** [AnKingMed/AnKing-Note-Types#84]
Cannot change the color of "Back" in the Basic-type notes. It is only white or black (dependent on night mode option), although it is set to blue by default
I reported this issue previously and you said it has been fixed. But still same problem.

**Comment by AnKingMed** [comment]
Sorry I missed this. It looks like the html for the back is 
`<div id="back">{{edit:Back}}</div>`
so you can add `#back` in the styling and do whatever you want with the color.  It looks like the cloze color is set to blue and that's just because it's reused code from the other note types, but that won't do anything on this note type as it's not a cloze.

Sorry for the delay on this!

**Comment by Farinata** [comment]
I don't understand what you are saying!
Please do the fix in an update.

**Comment by AnKingMed** [comment]
In the Styling of the note types (Click "Add" to add a new note -> then choose the note type -> then click "cards" -> then click the styling tab) you can add this at the bottom:
```
#back {
  color: black;
}
```
You can also replace black with any html color code from [this website](https://htmlcolorcodes.com/color-picker/) (i.e. `#021FFD`)
