### ISSUE TITLE
Needs Closet .js update

### ISSUE THREAD

**Issue by AnKingMed** [AnKingMed/AnKing-Note-Types#88]
We need to update to the new version of the closet css and js. I updated my note types using the Asset Manager and things started working again

**Comment by AnKingMed** [comment]
@RisingOrange can you update the note types and then the note types add-on?   IO-one by one and Physeo IO one by one will both need updates. I wasn't sure how to do it with the template files and then making sure that the css and js files will be available for people. I attached the js and css if that makes it easier.

Are you able to do this sometime soon?
 
[Archive.zip](https://github.com/AnKingMed/AnKing-Note-Types/files/9485428/Archive.zip)

**Comment by RisingOrange** [comment]
I updated the closet version on the note types from `0.5.3` to `0.6.1` (74c200d99550ebe28a3da004f941a400a89a1072) and updated the note types add-on so that it adds the `__closet-0.6.1.js` and `__closet-0.6.1.css` files to the media folder (https://github.com/AnKingMed/anking_notes_addon/releases/tag/1.2.18).

This means the IO note types will work if someone uses the note types with the current version of the Closet add-on (and without the AnKing note types add-on). The note types will stop working if a new version of Closet is released and you somehow lose the `__closet-0.6.1.js` and `.css` file from your media folder. 

That's why I would recommend to use the note types add-on which now adds these files to the media folder on Anki startup. If you do that, IO notes will still work even if Closet gets updated (if there are no breaking changes, in which chase we need to update the note types again).

**Comment by AnKingMed** [comment]
I'm getting this when I look in the note types manager and click closet, but it looks like everything else is working. Anything we need to do about this?

![image](https://user-images.githubusercontent.com/57678116/188498766-d04d8852-e0a5-467a-b0f9-d8d5974b7ac4.png)

**Comment by RisingOrange** [comment]
Wait, did you install the add-on from the GitHub release? I didn't upload it to AnkiWeb yet.

**Comment by AnKingMed** [comment]
I just uploaded it to AnkiWeb and then tested it. Looks like things are working and the note type is changed to reference 0.6.1, but for whatever reason this part still says the inserted closet is 0.5.3

**Comment by RisingOrange** [comment]
Oh ok. It probably won't cause any problems, but I'll check why it does that.

**Comment by AnKingMed** [comment]
Great thanks!
